---

services:
  bitwarden:
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    env_file:
      - settings.env
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test: ["CMD", "curl", "-f", "http://localhost:8080/alive"]
      timeout: 3s
    image: ${REGISTRY:-ghcr.io/bitwarden}/lite:${TAG:-beta}
    ports:
      - "80:8080"
      - "443:8443"
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden

  # MariaDB Example
  db:
    environment:
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_USER: "bitwarden"
    image: mariadb:10
    restart: always
    volumes:
      - data:/var/lib/mysql

  # PostgreSQL Example
  # db:
  #   environment:
  #     POSTGRES_DB: "bitwarden_vault"
  #     POSTGRES_PASSWORD: "super_strong_password"
  #     POSTGRES_USER: "bitwarden"
  #   image: postgres:14
  #   restart: always
  #   volumes:
  #     - data:/var/lib/postgresql/data

  # MS SQL Server Example
  # Docs: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment
  # db:
  #   environment:
  #     ACCEPT_EULA: Y
  #     MSSQL_SA_PASSWORD: "super_strong_password"
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   restart: always
  #   volumes:
  #     - data:/var/opt/mssql

volumes:
  bitwarden:
  data:
  logs:
