---

services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - settings.env
    image: ${REGISTRY:-ghcr.io/bitwarden}/lite:${TAG:-2025.12.2}
    user: 999:999
    tmpfs: /tmp:rw,noexec,nosuid,nodev,size=512m
    read_only: true
    security_opt:
      - no-new-privileges
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      # The user specified above must have permissions
      # for the bind mount on the host
      - bitwarden:/etc/bitwarden

  # MariaDB Example
  db:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: always
    volumes:
      - data:/var/lib/mysql

  # PostgreSQL Example
  # db:
  #   environment:
  #     POSTGRES_USER: "bitwarden"
  #     POSTGRES_PASSWORD: "super_strong_password"
  #     POSTGRES_DB: "bitwarden_vault"
  #   image: postgres:14
  #   restart: always
  #   volumes:
  #     - data:/var/lib/postgresql/data

  # MS SQL Server Example
  # Docs: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment
  # db:
  #   environment:
  #     MSSQL_SA_PASSWORD: "super_strong_password"
  #     ACCEPT_EULA: Y
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   restart: always
  #   volumes:
  #     - data:/var/opt/mssql

volumes:
  bitwarden:
  data:
